language: python
python:
  - "3.8"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - pylint src --errors-only